version: 2
jobs:
  build:
    docker:
      - image: "debian:stretch"
    parallelism: 1
    steps:
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt-get install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing GCC
          command: 'apt-get update && apt-get install -y gcc g++'
      - run:
          name: Install CMAKE
          command: 'apt-get update && sudo apt-get install -y cmake'
      - run:
          command: 'apt-get -qq update; apt-get -y install git'
      - checkout
      - run:
          name: Get boost
          command: 'sudo apt-get install libboost-all-dev -y'
      - run:
          name: Creating Build Files
          command: 'cmake -H. -Bbuild'
      - run:
          name: Creating Binary Files
          command: 'cmake --build build'
      - run:
          name: Run verification simulation
          command: './solver ShinMetiu/verify.config'
      - run:
          name: Compare results 
          command: './unit_tests'
      
